### ISSUE TITLE
id attributes on the generate <math> (for Formula Search). 

### ISSUE THREAD

**Issue by kohlhase** [parasew/instiki#34]
We are currently discussing adding a formula/keyword search facility to nlab.  For that it would be very helpful if the <math> elements would carry ```id``` attributes  (see the e-mail below). 

```
Dear Bas, dear all,

Here is the overall plan for enabling MathWebSearch on nlab, and nothing 
_needs_ to be changed for that, but there is room for improvement.

0. the current nlab situation:
   - nlab web pages are HTML with MathML generated by iTeX
   - MathML is presentation MathML and contains the original
      iTeX snippets for reference.
   - The MathML does not contain any id attributes.
1. the current MathWebSearch (MWS) Situation:
   - MWS indexes content MathML (natively) and bags of words (via ElasticSearch)
   - MWS needs the content in "MWS Harvests" (special format)
   - MWS has an UI that can be embedded into HTML pages (see [1])
   - MWS UI uses a LaTeXML (LaTeX->XML) daemon to transform
2. Obtaining MWS harvests for nlab
    - KWARC downloads nlab web pages
    - we run LaTeXML over the embedded iTeX snippets --> CMML
    - from page text and and CMML produce harvests (custom harvester)
3. Initial System Setup
    - KWARC provides a nlab search demo like [1] running on our servers
    - nlab provides a means of keeping the KWARC nlab copy up to date
       (e.g. nightly exports of the pages + change reports)
    - nlab links to the demo for community evaluation
4. Stable System (if nlab likes MWS)
    - nlab integrates MWS UI into nlab proper (or replaces by custom UI)
    - we migrate the MWS server and the LaTeXML server to nlab machines
    - tighter integration of the update process.

This experiment (up to 3.) can work out of the box with minimal effort from the nlab side: 
the only investment from nlab is the update process and we can even experiment 
with manual updates (re-download) for evaluation. In particular, no semantic markup is 
necessary on the nlab side.

There is one improvement to nlab I would like to suggest: adding id attributes to MathML.

Background:  Essentially, the MWS server is a daemon that takes Formula Schemata as 
input and gives URIs of the hits as output. Currently we only really have page URIs for this.
It would be much nicer to have URIs that point to particular formulae. This is possible with 
XPath, but having id attributes on Math formulae would simplify this considerably.

Concretely: change the first line in

<math class="maruku-mathml" display="inline" xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics>
    <mrow>
      <mi>X</mi>
      <mo>∈</mo>
      <mi>S</mi>
    </mrow>
    <annotation encoding="application/x-tex">X\in S</annotation>
  </semantics>
</math>

(copied from [2]) to

<math id="m315" class="maruku-mathml" display="inline" 
     xmlns="http://www.w3.org/1998/Math/MathML">

where the string "m3015" is unique in the page. This way, we could index 
https://ncatlab.org/nlab/show/indexed+category#m315 instead of mere [2] and 
use the fragment information e.g. for highlighting the results in the page. 
Even better would be to add such id attributes to all of the MathML sub-elements,
but that is optional. Adding id attributes is something that should be relatively easy 
to add to either iTeX or the page creation process.

I hope this helps you assess the situation.

Michael
```
[1] http://jupiter.eecs.jacobs-university.de/arxiv-ntcir/
[2] https://ncatlab.org/nlab/show/indexed+category

**Comment by distler** [comment]
It would be trivial to implement machine-generated `id`s for `<math>` elements.

But, before launching in, let me ask a few questions.

1. Instiki is *designed* to facilitate *nested* markup, for instance: mathml-in-svg-in-mathml-in-html. (Further levels of nesting are possible, but almost never occur in practice.) Do you want to generate `id`s for all of the nested `<math>` elements, or just for the "outermost" element?
2. In the context of Wikis, machine-generated `id`s as link-targets are **almost never** a good idea. Why? Because anytime someone edits the page, the `id`s get regenerated, and what was previously `<math id='m37'>` becomes `<math id='m39'>`. It's one thing when the user follows a link to a page and knows that he/she must search within that page for the phrase or equation they were looking for. It's quite another thing, when the link points to a fragment-identifier on the page, but it's the *wrong*  fragment identifier.

  *Human*-generated `id`s, by contrast, precisely because they are intentional, tend to survive minor edits. So I'd be far more confident that `https://ncatlab.org/nlab/show/indexed+category#CanonicalSelfIndexing` (a real example) will continue to work in subsequent revisions of that page, whereas a hypothetical `https://ncatlab.org/nlab/show/indexed+category#m37` is pretty much guaranteed to break (i.e., point to the wrong `<math>` fragment) the next time someone edits the page.

**Comment by kohlhase** [comment]
thanks for the quick answer. 
1. it would be best to have ids on all <math> elements. 
2. I generally agree with this, but I think your caveat only applies to ''human-generated'' references. The situation is different for the application of a search engine, which regularly re-indexes all changed documents (machine-generated references). I do  see however that having ids on math elements might tempt humans to reference them. I do believe that if that becomes a problem, it should be solved by adding a TeX-based id mechanism (but this is a different problem).

**Comment by distler** [comment]
Done.

The feature is turned-off by default. To turn it on:

Do a

```
ruby bundle update
```
to get the latest revision of our branch of Maruku.  Then edit `lib/chunks/engines.rb` to turn it on.

```
--- lib/chunks/engines.rb	2012-07-26 16:14:24 +0000
+++ lib/chunks/engines.rb	2016-05-06 02:55:35 +0000
@@ -64,6 +64,7 @@
       if @content.options[:mode] == :s5
         my_content = Maruku.new(text,
                            {:math_enabled => true,
+                            :html_math_generate_ids => true,
                             :math_numbered => ['\\[','\\begin{equation}'],
                             :content_only => true,
                             :author => @content.options[:engine_opts][:author],
@@ -74,6 +75,7 @@
         (t = Time.now; nil)
         html = Maruku.new(text,
              {:math_enabled => true,
+              :html_math_generate_ids => true,
               :math_numbered => ['\\[','\\begin{equation}']}).to_html
         (ApplicationController.logger.info("Maruku took " + (Time.now-t).to_s + " seconds."); nil)
         html.gsub(/\A<div class="maruku_wrapper_div">\n?(.*?)\n?<\/div>\Z/m, '\1')
```

Note: *By design*, the `id`s will change whenever the page is edited. This addresses my original concern.

It will be your responsibility to ensure that the search-engine is kept in sync with revisions of the wiki. But you indicated that would not be a problem :-).
