### ISSUE TITLE
Simple way to disable MathJax?

### ISSUE THREAD

**Issue by casper** [parasew/instiki#72]
Is there any simple way to disable MathJax so that I can safely delete the `public/MathJax` folder?

I run Instiki on a minimal VPS, and it would be nice to be able to save 200M of space if MathJax could be deleted when it is not in use.

Any way to accomplish that, or can I just go ahead and delete `public/MathJax` anyway?

**Comment by distler** [comment]
The worst that will happen is that

1. Non-MathML capable browsers (e.g. Chrome) will fail to render the math.
2. The attempt to load the MathJax javascript will fail in those browsers (producing a javascript error in the console).

Because of (1), (2) won't be the most annoying thing about the browser experience.

It's certainly easy to modify `app/views/layouts/default.rhtml` to fix (2). (Or, if you're not actually using using math, just publish your webs as `markdown` instead of `markdownMML`.)

**Comment by casper** [comment]
Ok. I think this is enough info that I will be able to make it work. The code in `default.rhtml` looks simple to fix if required. I just needed to know where to look :) Thanks.
